apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
  type: NodePort
  selector:
    app: spring-petclinic
  ports:
    - protocol: TCP
      port: 80              # Cluster-internal port for the Service
      targetPort: 8080       # Port on the container that the service forwards to
      nodePort: 30007        # NodePort you can access externally (choose an available port in the range 30000–32767)
